// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqo0iAf9Ot-QPPpuqarn5w0ril_6a-QxQ',
    appId: '1:557419998124:web:0921e7dcb90bf5119b2809',
    messagingSenderId: '557419998124',
    projectId: 'task-management-62e13',
    authDomain: 'task-management-62e13.firebaseapp.com',
    storageBucket: 'task-management-62e13.firebasestorage.app',
    measurementId: 'G-86LPRFZS9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK14pKa4urGpfhBe_qaauzVQGOpfOEo9M',
    appId: '1:557419998124:android:59885265dff70ece9b2809',
    messagingSenderId: '557419998124',
    projectId: 'task-management-62e13',
    storageBucket: 'task-management-62e13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOCdYStnwMYZyDtkvWOaYZh-TqOYDdhrU',
    appId: '1:557419998124:ios:b598c5ea02b64e6e9b2809',
    messagingSenderId: '557419998124',
    projectId: 'task-management-62e13',
    storageBucket: 'task-management-62e13.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOCdYStnwMYZyDtkvWOaYZh-TqOYDdhrU',
    appId: '1:557419998124:ios:b598c5ea02b64e6e9b2809',
    messagingSenderId: '557419998124',
    projectId: 'task-management-62e13',
    storageBucket: 'task-management-62e13.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqo0iAf9Ot-QPPpuqarn5w0ril_6a-QxQ',
    appId: '1:557419998124:web:aae702319fd28fa29b2809',
    messagingSenderId: '557419998124',
    projectId: 'task-management-62e13',
    authDomain: 'task-management-62e13.firebaseapp.com',
    storageBucket: 'task-management-62e13.firebasestorage.app',
    measurementId: 'G-NKXGYS9E52',
  );
}
